development:
  adapter: postgresql
  encoding: unicode
  database: congress_development
  host: localhost
  pool: 5
  # username: deployment
  # password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: car2yo_test
  host: localhost
  pool: 5
  # username: deployment
  # password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: congress
  host: localhost
  pool: 5
  # username: deployment
  # password: <%= ENV['DB_PASSWORD'] %>
