development:
  adapter: postgresql
  encoding: unicode
  database: congress_development
  host: localhost
  pool: 5
  username: deployment
  password: <%= ENV['DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: congress_test
  host: localhost
  pool: 5
  username: deployment
  password: <%= ENV['DB_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: congress
  host: localhost
  pool: 5
  username: deployment
  password: <%= ENV['DB_PASSWORD'] %>
